version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: laravel/framework
    versions:
    - 8.26.1
    - 8.27.0
    - 8.28.1
    - 8.29.0
    - 8.30.0
    - 8.30.1
    - 8.31.0
    - 8.32.1
    - 8.33.1
    - 8.34.0
    - 8.35.1
    - 8.36.1
    - 8.36.2
    - 8.37.0
    - 8.38.0
    - 8.39.0
  - dependency-name: laravel/sail
    versions:
    - 1.3.1
    - 1.4.1
    - 1.4.10
    - 1.4.11
    - 1.4.12
    - 1.4.3
    - 1.4.4
    - 1.4.6
    - 1.4.7
    - 1.4.8
    - 1.4.9
    - 1.5.0
  - dependency-name: facade/ignition
    versions:
    - 2.5.10
    - 2.5.11
    - 2.5.12
    - 2.5.13
    - 2.5.14
    - 2.6.0
    - 2.7.0
    - 2.8.2
    - 2.8.3
  - dependency-name: barryvdh/laravel-debugbar
    versions:
    - 3.5.4
    - 3.5.5
  - dependency-name: beyondcode/laravel-websockets
    versions:
    - 1.10.0
    - 1.11.0
    - 1.11.1
    - 1.12.0
  - dependency-name: laravel/dusk
    versions:
    - 6.11.3
    - 6.12.0
    - 6.13.0
    - 6.14.0
    - 6.15.0
  - dependency-name: fakerphp/faker
    versions:
    - 1.14.0
    - 1.14.1
  - dependency-name: guzzlehttp/guzzle
    versions:
    - 7.3.0
  - dependency-name: laravel/tinker
    versions:
    - 2.6.1
  - dependency-name: mockery/mockery
    versions:
    - 1.4.3
